/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculator.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <signal.h>
#include <sys/ioctl.h> /* ioctl, TIOCNOTTY */
#include <sys/types.h> /* open */
#include <sys/stat.h> /* open */
#include <fcntl.h> /* open */
#include <unistd.h> /* getdtablesize */
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

#define _RPCSVC_CLOSEDOWN 120
 int _rpcpmstart;		/* Started by a port monitor ? */
 int _rpcfdtype;		/* Whether Stream or Datagram ? */
 /* States a server can be in wrt request */

#define	_IDLE 0
#define	_SERVED 1
#define	_SERVING 2

static int _rpcsvcstate = _IDLE;	 /* Set when a request is serviced */

static
void _msgout (char* msg)
{
#ifdef RPC_SVC_FG
	if (_rpcpmstart)
		syslog (LOG_ERR, "%s", msg);
	else
		fprintf (stderr, "%s\n", msg);
#else
	syslog (LOG_ERR, "%s", msg);
#endif
}

static void
closedown (int sig)
{
	if (_rpcsvcstate == _IDLE) {
		extern fd_set svc_fdset;
		static int size;
		int i, openfd;

		if (_rpcfdtype == SOCK_DGRAM)
			exit (0);
		if (size == 0) {
			size = getdtablesize();
		}
		for (i = 0, openfd = 0; i < size && openfd < 2; i++)
			if (FD_ISSET(i, &svc_fdset))
				openfd++;
		if (openfd <= 1)
			exit (0);
	}
	if (_rpcsvcstate == _SERVED)
		_rpcsvcstate = _IDLE;

	(void) signal(SIGALRM, (SIG_PF) closedown);
	alarm (_RPCSVC_CLOSEDOWN);
}

static void
calculator_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		intpair add_1_arg;
		intpair subtract_1_arg;
		intpair multiply_1_arg;
		intpair divide_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	_rpcsvcstate = _SERVING;
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		_rpcsvcstate = _SERVED;
		return;

	case ADD:
		_xdr_argument = (xdrproc_t) xdr_intpair;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) add_1_svc;
		break;

	case SUBTRACT:
		_xdr_argument = (xdrproc_t) xdr_intpair;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) subtract_1_svc;
		break;

	case MULTIPLY:
		_xdr_argument = (xdrproc_t) xdr_intpair;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) multiply_1_svc;
		break;

	case DIVIDE:
		_xdr_argument = (xdrproc_t) xdr_intpair;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) divide_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		_rpcsvcstate = _SERVED;
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		_rpcsvcstate = _SERVED;
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		_msgout ("unable to free arguments");
		exit (1);
	}
	_rpcsvcstate = _SERVED;
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;
	int sock;
	int proto;
	struct sockaddr_in saddr;
	int asize = sizeof (saddr);

	if (getsockname (0, (struct sockaddr *)&saddr, &asize) == 0) {
		int ssize = sizeof (int);

		if (saddr.sin_family != AF_INET)
			exit (1);
		if (getsockopt (0, SOL_SOCKET, SO_TYPE,
				(char *)&_rpcfdtype, &ssize) == -1)
			exit (1);
		sock = 0;
		_rpcpmstart = 1;
		proto = 0;
		openlog("calculator", LOG_PID, LOG_DAEMON);
	} else {
#ifndef RPC_SVC_FG
		int size;
		int pid, i;

		pid = fork();
		if (pid < 0) {
			perror("cannot fork");
			exit(1);
		}
		if (pid)
			exit(0);
		size = getdtablesize();
		for (i = 0; i < size; i++)
			(void) close(i);
		i = open("/dev/console", 2);
		(void) dup2(i, 1);
		(void) dup2(i, 2);
		i = open("/dev/tty", 2);
		if (i >= 0) {
			(void) ioctl(i, TIOCNOTTY, (char *)NULL);
			(void) close(i);
		}
		openlog("calculator", LOG_PID, LOG_DAEMON);
#endif
		sock = RPC_ANYSOCK;
		pmap_unset (CALCULATOR_PROG, CALCULATOR_VERS);
	}

	if ((_rpcfdtype == 0) || (_rpcfdtype == SOCK_DGRAM)) {
		transp = svcudp_create(sock);
		if (transp == NULL) {
			_msgout ("cannot create udp service.");
			exit(1);
		}
		if (!_rpcpmstart)
			proto = IPPROTO_UDP;
		if (!svc_register(transp, CALCULATOR_PROG, CALCULATOR_VERS, calculator_prog_1, proto)) {
			_msgout ("unable to register (CALCULATOR_PROG, CALCULATOR_VERS, udp).");
			exit(1);
		}
	}

	if ((_rpcfdtype == 0) || (_rpcfdtype == SOCK_STREAM)) {
		transp = svctcp_create(sock, 0, 0);
		if (transp == NULL) {
			_msgout ("cannot create tcp service.");
			exit(1);
		}
		if (!_rpcpmstart)
			proto = IPPROTO_TCP;
		if (!svc_register(transp, CALCULATOR_PROG, CALCULATOR_VERS, calculator_prog_1, proto)) {
			_msgout ("unable to register (CALCULATOR_PROG, CALCULATOR_VERS, tcp).");
			exit(1);
		}
	}

	if (transp == (SVCXPRT *)NULL) {
		_msgout ("could not create a handle");
		exit (1);
	}
	if (_rpcpmstart) {
		(void) signal (SIGALRM, (SIG_PF) closedown);
		(void) alarm (_RPCSVC_CLOSEDOWN);
	}
	svc_run ();
	_msgout ("svc_run returned");
	exit (1);
	/* NOTREACHED */
}
