/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "calculator.h"

void calculator_prog_1(char *host, char *expr) {
    CLIENT *clnt;
    intpair args;
    int *res_int;
    float *res_float;

    clnt = clnt_create(host, CALCULATOR_PROG, CALCULATOR_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }

    // Parse expr like "1+2"
    int a = 0, b = 0;
    char op = 0;
    if (sscanf(expr, "%d%c%d", &a, &op, &b) != 3) {
        fprintf(stderr, "Invalid expression format: %s\n", expr);
        exit(1);
    }

    args.a = a;
    args.b = b;

    int *result_int = NULL;
    float *result_float = NULL;

    switch(op) {
        case '+':
            result_int = add_1(&args, clnt);
            if (result_int != NULL) printf("Add: %d\n", *result_int);
            else clnt_perror(clnt, "Add RPC failed");
            break;
        case '-':
            result_int = subtract_1(&args, clnt);
            if (result_int != NULL) printf("Subtract: %d\n", *result_int);
            else clnt_perror(clnt, "Subtract RPC failed");
            break;
        case '*':
            result_int = multiply_1(&args, clnt);
            if (result_int != NULL) printf("Multiply: %d\n", *result_int);
            else clnt_perror(clnt, "Multiply RPC failed");
            break;
        case '/':
            result_float = divide_1(&args, clnt);
            if (result_float != NULL) printf("Divide: %.2f\n", *result_float);
            else clnt_perror(clnt, "Divide RPC failed");
            break;
        default:
            fprintf(stderr, "Unknown operator: %c\n", op);
            break;
    }

    clnt_destroy(clnt);
}

int main(int argc, char *argv[]) {
    if (argc != 3) {
        printf("Usage: %s <server_host> <expr>\n", argv[0]);
        printf("Example: %s localhost 1+2\n", argv[0]);
        exit(1);
    }
    calculator_prog_1(argv[1], argv[2]);
    return 0;
}
